version: '3'

services:

  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - frontend
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    image: vue
    container_name: vue
    build:
      context: ./vue
    ports:
      - 8080:80
    restart: on-failure